name: "NeuVector Cluster"
description: "Install NeuVector on kuberentes cluster"
author: ""

inputs:
  Namespace:
    description: "Kubernetes namespace to install NeuVector."
    required: false
    default: "neuvector"

  HelmRepo:
    description: "NeuVector Helm repo URL."
    required: false
    default: "https://neuvector.github.io/neuvector-helm/"

  RepoName:
    description: "Name to assign to the Helm repo."
    required: false
    default: "neuvector"

  ChartName:
    description: "Helm chart name for NeuVector."
    required: false
    default: "neuvector/core"

  Version:
    description: "NeuVector product version (sets --set tag=<version>). Example: 5.4.2"
    required: false
    default: ""

  LabelNamespacePrivileged:
    description: "Label namespace with pod-security=privileged for PSA-enabled clusters."
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Repo checkout
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "latest"

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: "latest"

    - name: Ensure namespace exists
      shell: bash
      run: |
        set -euo pipefail
        NS="${{ inputs.Namespace }}"
        if ! kubectl get ns "${NS}" >/dev/null 2>&1; then
          kubectl create ns "${NS}"
          echo "Namespace ${NS} created"
        else
          echo "Namespace ${NS} already exists"
        fi

    - name: Label namespace privileged (PSA)
      if: ${{ inputs.LabelNamespacePrivileged == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        NS="${{ inputs.Namespace }}"
        kubectl label namespace "${NS}" \
          "pod-security.kubernetes.io/enforce=privileged" --overwrite
        echo "Namespace ${NS} labeled privileged"

    - name: Add Helm repo
      if: ${{ inputs.HelmRepo != '' }}
      shell: bash
      run: |
        set -euo pipefail
        helm repo add ${{ inputs.RepoName }} "${{ inputs.HelmRepo }}" || true
        helm repo update

    - name: Install NeuVector with version mapping
      shell: bash
      run: |
        set -euo pipefail
        
        VERSION="${{ inputs.Version }}"

        declare -A CHART_MAP=(
          ["5.4.7"]="2.8.9"
          ["5.4.6"]="2.8.8"
          ["5.4.5"]="2.8.7"
          ["5.4.4"]="2.8.6"
          ["5.4.3"]="2.8.5"
          ["5.4.2"]="2.8.4"
          ["5.4.1"]="2.8.3"
          ["5.4.0"]="2.8.2"
        )

        if [[ -z "$VERSION" ]]; then
          echo "No version specified → Installing latest chart"
          helm install neuvector neuvector/core \
            --namespace neuvector --create-namespace
          exit 0
        fi

        if [[ -z "${CHART_MAP[$VERSION]+x}" ]]; then
          echo "❌ ERROR: Unknown APP version: $VERSION"
          exit 1
        fi

        CHART_VERSION="${CHART_MAP[$VERSION]}"

    - name: Installing NeuVector
      shell: bash
      run: |
        helm upgrade --install neuvector neuvector/core --namespace ${{ inputs.Namespace }}  --version "$CHART_VERSION" --create-namespace ${SET_TAG} 
        
branding:
  icon: "shield"
  color: "green"
